apiVersion: apps/v1
kind: Deployment
metadata:
  name: info
spec:
  selector:
    matchLabels:
      app: info
  template:
    metadata:
      labels:
        app: info
    spec:
      containers:
        - name: appinfo
          image: appinfo:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - configMapRef:
            name: info-conf
